name: zitadel
version: 3.0.36
description: >-
  Dart package for ZITADEL relatet matters. Contains the compiled grpc service clients
  to access the ZITADEL API.
repository: https://github.com/caos/zitadel-dart
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  grpc: ^3.0.2
  http: ^0.13.5
  jose: ^0.3.2
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  path: ^1.8.3
  test: ^1.21.6
