name: Release Package

on:
  push:
    branches:
      - main
      - next

jobs:
  package_and_publish:
    name: Package and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: just install-tools
      - run: dart pub get
      - run: just
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
