name: Test Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint_and_test:
    strategy:
      fail-fast: true
      matrix:
        sdk:
          - 2.18.0
          - stable
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: enable protoc dart
        run: dart pub global activate protoc_plugin
      - name: build gRPC
        run: ./tool/generate_grpc.sh
      - run: dart pub get
      - name: build barrel files
        run: ./tool/generate_barrel_files.dart
      - run: dart analyze
      - run: dart test

  test_result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test and Lint Results
    needs: [lint_and_test]
    steps:
      - run: |
          result="${{ needs.lint_and_test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi

  publish_dryrun:
    name: Show publish dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: enable protoc dart
        run: dart pub global activate protoc_plugin
      - run: dart pub get
      - name: build gRPC
        run: ./tool/generate_grpc.sh
      - name: build barrel files
        run: ./tool/generate_barrel_files.dart
      - run: echo '### Publish Pub Package Result' >> $GITHUB_STEP_SUMMARY
      - run: dart pub publish --dry-run >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
      - run: echo '' >> $GITHUB_STEP_SUMMARY
