name: Test Package

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: just install-tools
      - run: dart pub get
      - run: just
      - run: dart analyze
      - run: dart test

  test_result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test and Lint Results
    needs: [lint_and_test]
    steps:
      - run: |
          result="${{ needs.lint_and_test.result }}"
          if [[ $result == "success" || $result == "skipped" ]]; then
            exit 0
          else
            exit 1
          fi

  publish_dryrun:
    name: Show publish dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: just install-tools
      - run: dart pub get
      - run: just
      - run: echo '### Publish Pub Package Result' >> $GITHUB_STEP_SUMMARY
      - run: dart pub publish --dry-run >> $GITHUB_STEP_SUMMARY
        continue-on-error: true
      - run: echo '' >> $GITHUB_STEP_SUMMARY
